apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: student-management-postgres
  namespace: student-management
  labels:
    app: student-management-postgres
spec:
  serviceName: student-management-postgres
  replicas: 1
  selector:
    matchLabels:
      app: student-management-postgres
  template:
    metadata:
      labels:
        app: student-management-postgres
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:18
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: student-management-postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: student-management-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-management-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            exec:
              command: ["pg_isready", "-U", "student_admin", "-d", "student_management"]
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "student_admin", "-d", "student_management"]
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "student_admin", "-d", "student_management"]
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: student-management-postgres-pvc
