apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-management-postgres-pvc
  namespace: student-management
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
